apiVersion: v1
kind: Service
metadata:
  name: qing-long
  labels:
    app: qing-long
spec:
  ports:
    - port: 8801
      targetPort: 8801
      name: qing-long-db-service
  selector:
    app: qing-long
    tier: smart-home-db
  externalIPs:
    - 192.168.42.101
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qing-long-pv-claim
  labels:
    app: qing-long
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qing-long
  labels:
    app: qing-long
    tier: smart-home-db
spec:
  selector:
    matchLabels:
      app: qing-long
      tier: smart-home-db
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qing-long
        tier: smart-home-db
    spec:
      containers:
        - image: rootthekid/qing-long:latest
          name: qing-long
          env:
            - name: NODE_ENV
              value: "prod"
            - name: ADDRESS
              value: "0.0.0.0"
            - name: SWAGGER_ADDRESS
              value: "192.168.42.101"
            - name: PORT
              value: "8801"
          volumeMounts:
            - name: qing-long-persistent-storage
              mountPath: /usr/src/app/db
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
      volumes:
        - name: qing-long-persistent-storage
          persistentVolumeClaim:
            claimName: qing-long-pv-claim
